import 'package:e_commerce/src/module/home/domain/entities/product_entity.dart';

class ProductData {
  List<ProductEntity> allSaleProducts = [
    const ProductEntity(
      productID: '0',
      brand: 'Polo',
      item: 'T-shirts',
      rating: 5,
      totalUser: 100,
      price: 60,
      newPrice: 45,
      isFavorite: true,
      isSale: true,
      sale: 15,
      isNew: false,
      photoURL:
          'https://www.seekpng.com/png/detail/70-707010_collar-polo-t-shirts-collar-t-shirt-png.png',
    ),
    const ProductEntity(
      productID: '1',
      brand: 'Polo',
      item: 'T-shirts',
      rating: 4,
      totalUser: 60,
      price: 50,
      newPrice: 40,
      isFavorite: false,
      isSale: true,
      sale: 15,
      isNew: false,
      photoURL:
          'https://i.pinimg.com/736x/4a/2d/94/4a2d94cab5ae4d769e4270e94ab935c0.jpg',
    ),
    const ProductEntity(
      productID: '2',
      brand: 'ISCO',
      item: 'Jeans  ',
      rating: 3,
      totalUser: 10,
      price: 100,
      newPrice: 80,
      isFavorite: false,
      isSale: true,
      sale: 20,
      isNew: false,
      photoURL:
          'https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/Search/224x336/530205.jpg',
    ),
    const ProductEntity(
      productID: '3',
      brand: 'Nike',
      item: 'Sneakers',
      rating: 2,
      totalUser: 10,
      price: 75,
      newPrice: 50,
      isFavorite: false,
      isSale: true,
      sale: 25,
      isNew: false,
      photoURL:
          'https://assets.hermes.com/is/image/hermesproduct/crew-sneaker--211109Z%2090-front-1-300-0-320-320_b.jpg',
    ),
    const ProductEntity(
      productID: '4',
      brand: 'Nike',
      item: 'Hoody ',
      rating: 1,
      totalUser: 10,
      price: 45,
      newPrice: 35,
      isFavorite: false,
      isSale: true,
      sale: 10,
      isNew: false,
      photoURL: 'https://m.media-amazon.com/images/I/3142AyjPF4L.jpg',
    ),
  ];

  List<ProductEntity> allNewProducts = [
    const ProductEntity(
      productID: '0',
      brand: 'Adidas',
      item: 'Hoody ',
      rating: 5,
      totalUser: 10,
      price: 80,
      newPrice: 0,
      isFavorite: false,
      isSale: false,
      sale: 0,
      isNew: true,
      photoURL:
          'https://cdn.idealo.com/folder/Product/6413/4/6413460/s1_produktbild_gross/tommy-hilfiger-regular-fit-zipped-hoody-dm0dm04400.jpg',
    ),
    const ProductEntity(
      productID: '1',
      brand: 'Gucci',
      item: 'Dress',
      rating: 4,
      totalUser: 10,
      price: 75,
      newPrice: 0,
      isFavorite: false,
      isSale: false,
      sale: 0,
      isNew: true,
      photoURL:
          'https://i.pinimg.com/736x/91/e0/b3/91e0b328e68411ac76f8fc7a9b09f125.jpg',
    ),
    const ProductEntity(
      productID: '2',
      brand: 'Gucci',
      item: 'Jacket',
      rating: 3,
      totalUser: 10,
      price: 90,
      newPrice: 0,
      isFavorite: false,
      isSale: false,
      sale: 0,
      isNew: true,
      photoURL:
          'https://sc02.alicdn.com/kf/U99d002376da84ad7a08856cba3f196ffn.jpg',
    ),
    const ProductEntity(
      productID: '3',
      brand: 'Adidas',
      item: 'Cap',
      rating: 2,
      totalUser: 10,
      price: 20,
      newPrice: 0,
      isFavorite: false,
      isSale: false,
      sale: 0,
      isNew: true,
      photoURL:
          'https://5.imimg.com/data5/IJ/UV/MY-43557180/black-fashion-caps-500x500.jpg',
    ),
    const ProductEntity(
      productID: '4',
      brand: 'Gucci',
      item: 'shirt',
      rating: 1,
      totalUser: 10,
      price: 70,
      newPrice: 0,
      isFavorite: false,
      isSale: false,
      sale: 0,
      isNew: true,
      photoURL:
          'https://ae01.alicdn.com/kf/H08a511a149974404ae82f82ac7fea9f9m/Vintage-Omar-Little-The-Wire-T-Shirt-2019-Unisex-Tees.jpg_640x640.jpg',
    ),
  ];
}
