name: e_commerce
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #state management
  flutter_bloc: ^8.1.1
  bloc: ^8.0.3

  #remote data
  firebase_core: ^1.20.0
  cloud_firestore: ^3.1.7
  firebase_auth: ^3.3.6
  firebase_storage: ^10.2.7
  google_sign_in: ^5.2.4

  #local data
  shared_preferences: ^2.0.13

  #DI
  get_it: ^7.2.0

  # Functional programming thingies
  dartz: ^0.10.1
  equatable: ^2.0.5

  #images, gallery, video
  image_picker: ^0.8.4+8

  #svg, icon, font
  flutter_svg: 1.0.1
  google_fonts: 2.2.0
  font_awesome_flutter: ^9.2.0
  country_icons: ^2.0.2
  fluttericon: ^2.0.0

  # navigation
  go_router: ^4.2.7

  #others
  pin_code_fields: ^7.4.0
  email_validator: ^2.0.1
  top_snackbar_flutter: ^2.1.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/png/illustrations/
    - assets/png/icons/
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
