// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM-OUGRv1RGpxm3GipGjCJRjXjDiGDsjc',
    appId: '1:113719629632:web:4ae6b6d706387551f1cca5',
    messagingSenderId: '113719629632',
    projectId: 'e-commerce-dab1e',
    authDomain: 'e-commerce-dab1e.firebaseapp.com',
    storageBucket: 'e-commerce-dab1e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKYWVCnZa9rrYUqvhLAHQXR-sxAONJlHU',
    appId: '1:113719629632:android:7a4d14d0e4a7ab92f1cca5',
    messagingSenderId: '113719629632',
    projectId: 'e-commerce-dab1e',
    storageBucket: 'e-commerce-dab1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgj55HMIdGwIbxHZsTrOMHHU6bqjQobz4',
    appId: '1:113719629632:ios:a48b267867624545f1cca5',
    messagingSenderId: '113719629632',
    projectId: 'e-commerce-dab1e',
    storageBucket: 'e-commerce-dab1e.appspot.com',
    androidClientId: '113719629632-buve15jkufdqnkr13jtifc5ceivh9vu5.apps.googleusercontent.com',
    iosClientId: '113719629632-c05gm42ueueplf2nh0dcutj19i1td79u.apps.googleusercontent.com',
    iosBundleId: 'com.aziko.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgj55HMIdGwIbxHZsTrOMHHU6bqjQobz4',
    appId: '1:113719629632:ios:a48b267867624545f1cca5',
    messagingSenderId: '113719629632',
    projectId: 'e-commerce-dab1e',
    storageBucket: 'e-commerce-dab1e.appspot.com',
    androidClientId: '113719629632-buve15jkufdqnkr13jtifc5ceivh9vu5.apps.googleusercontent.com',
    iosClientId: '113719629632-c05gm42ueueplf2nh0dcutj19i1td79u.apps.googleusercontent.com',
    iosBundleId: 'com.aziko.eCommerce',
  );
}
